import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { eq } from 'drizzle-orm';
import { expect, it, vi } from 'vitest';
import { buildServer, type AccServer } from '../app';
import { openDb } from '../db';
import { runs, operationApprovals } from '../db/schema';
import { workspaceEvidence } from './workspace';

it('requires an authenticated, current, operation-specific review and records its single consumption through the API', async () => {
  const root = mkdtempSync(join(tmpdir(), 'controlos-review-api-'));
  const repo = join(root, 'repo'); mkdirSync(repo);
  const git = (args: string[]) => execFileSync('git', args, { cwd: repo, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  const database = openDb(join(root, 'profile.sqlite'));
  let server: AccServer | undefined;
  const host = { host: '127.0.0.1:8787' };
  const auth = { ...host, 'x-acc-token': 'review-fixture-key' };
  try {
    git(['init', '-q']); git(['config', 'user.name', 'Fixture']); git(['config', 'user.email', 'fixture@example.test']);
    writeFileSync(join(repo, 'package.json'), JSON.stringify({ scripts: { verify: 'node verify.cjs' } }));
    writeFileSync(join(repo, 'verify.cjs'), 'process.exitCode=0');
    git(['add', '.']); git(['commit', '-qm', 'fixture']);
    const baseSha = git(['rev-parse', 'HEAD']);
    const result = await workspaceEvidence(repo, baseSha);
    database.db.insert(runs).values({ id: 'review-run', repoId: 'review-repo', task: 'Offline review fixture', model: 'default', status: 'done', engineVersion: 1, startedTs: new Date().toISOString(), workspacePath: repo, baseSha, ...result }).run();
    server = await buildServer({ port: 8787, webOrigin: 'http://localhost:5173', accToken: 'review-fixture-key', dbPath: join(root, 'profile.sqlite'), projectDirs: [], demo: false }, { startSystem: false });
    server.bus.publish({ id: 'review-repo-fixture', type: 'repo.upserted', ts: new Date().toISOString(), source: { kind: 'scanner', ref: 'fixture' }, payload: { repo: { id: 'review-repo', name: 'Offline review', category: 'app', status: 'active', description: 'Fixture', branch: 'fixture', updatedTs: new Date().toISOString() } } });
    const app = server.app;
    const post = (suffix: string, body: Record<string, unknown>) => app.inject({ method: 'POST', url: `/api/runs/review-run/${suffix}`, headers: auth, payload: body });
    const detail = async () => (await app.inject({ url: '/api/runs/review-run', headers: auth })).json().run;
    const target = async () => ({ ...result, operation: 'result.accept', policyVersion: (await detail()).approvalPolicyVersion });
    const prepare = async () => {
      const reviewed = await target();
      const response = await post('approval', reviewed);
      expect(response.statusCode, response.body).toBe(200);
      return { ...reviewed, action: 'accepted', approvalId: response.json().approval.id };
    };
    for (const suffix of ['approval', 'outcome']) expect((await app.inject({ method: 'POST', url: `/api/runs/review-run/${suffix}`, headers: host, payload: {} })).statusCode).toBe(401);
    expect((await post('verify', {})).statusCode).toBe(200);
    expect((await post('outcome', { action: 'accepted', ...await target() })).statusCode).toBe(409);
    expect((await post('approval', { ...await target(), operation: 'deploy' })).statusCode).toBe(400);
    const old = await prepare();
    expect((await post('outcome', { ...old, action: 'corrected' })).statusCode).toBe(400);
    for (const enabled of [false, true]) expect((await app.inject({ method: 'POST', url: '/api/projects/review-repo/settings', headers: auth, payload: { feature: 'notifications', enabled } })).statusCode).toBe(200);
    expect((await post('outcome', old)).statusCode).toBe(409);
    expect((await detail()).approvalPolicyVersion).not.toBe(old.policyVersion);
    expect((await detail()).humanAction).toBeNull();
    const changed = await prepare();
    writeFileSync(join(repo, 'verify.cjs'), 'process.exitCode=1');
    expect((await post('outcome', changed)).statusCode).toBe(409);
    expect((await detail()).verifyVerdict).toBeNull();
    expect(database.db.select().from(operationApprovals).where(eq(operationApprovals.id, changed.approvalId)).get()?.revokedTs).not.toBeNull();
    writeFileSync(join(repo, 'verify.cjs'), 'process.exitCode=0');
    expect((await post('verify', {})).statusCode).toBe(200);
    const superseded = await prepare();
    expect((await post('verify', {})).statusCode).toBe(200);
    expect((await post('outcome', superseded)).statusCode).toBe(409);
    const current = await prepare();
    const template = await app.inject({ method: 'POST', url: '/api/testflight/profiles', headers: auth, payload: { repoId: 'review-repo', name: 'Review isolation fixture', scheme: 'Fixture', bundleId: 'test.fixture' } });
    expect(template.statusCode, template.body).toBe(200);
    const profile = template.json().profile;
    const dispatch = vi.spyOn(server.runner, 'dispatch');
    try {
      const reused = await app.inject({ method: 'POST', url: `/api/testflight/profiles/${profile.id}/deploy`, headers: auth, payload: { marketingVersion: '1.0', buildNumber: '1', ...current } });
      expect(reused.statusCode, reused.body).toBe(400);
      expect(reused.json().error).toContain('approvals cannot authorize deployment');
      expect(dispatch).not.toHaveBeenCalled();
      expect((await app.inject({ url: '/api/testflight/profiles', headers: auth })).json().profiles).toEqual([profile]);
      expect(database.db.select().from(operationApprovals).where(eq(operationApprovals.id, current.approvalId)).get()).toMatchObject({ consumedTs: null, revokedTs: null });
    } finally { dispatch.mockRestore(); }
    expect((await post('outcome', current)).statusCode).toBe(200);
    expect((await post('outcome', current)).statusCode).toBe(409);
    const final = await detail();
    expect(final.humanAction).toBe('accepted');
    expect(final.approvalHistory.filter((r: { consumedTs: string | null }) => r.consumedTs)).toHaveLength(1);
    expect(final.approvalHistory.find((r: { id: string }) => r.id === current.approvalId)).toMatchObject({ operation: 'result.accept', actorId: 'local-owner', headSha: result.headSha, diffDigest: result.diffDigest, policyVersion: current.policyVersion });
    const savedPolicy = JSON.parse(final.approvalHistory.find((r: { id: string }) => r.id === current.approvalId).policySnapshot);
    const settings = (await app.inject({ url: '/api/projects/review-repo/settings', headers: auth })).json().features;
    expect(Object.fromEntries(savedPolicy.features)).toEqual(settings);
  } finally { await server?.close(); database.sqlite.close(); await rm(root, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 }); }
}, 120000);
