import { execFileSync, spawn } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { rm } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expect, it } from 'vitest';
import { buildServer, type AccServer } from '../app';
import type { Spawner } from './spawner';

it('T05: binds an exact task revision to an isolated real exit-zero process and persists awaiting_review rather than acceptance', async () => {
  const root = mkdtempSync(join(tmpdir(), 'controlos-task-run-api-')), repo = join(root, 'repo'); mkdirSync(repo);
  const git = (args: string[]) => execFileSync('git', args, { cwd: repo, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  const host = { host: '127.0.0.1:8787' }, auth = { ...host, 'x-acc-token': 'task-run-fixture-key' };
  const env = { port: 8787, webOrigin: 'http://localhost:5173', accToken: auth['x-acc-token'], dbPath: join(root, 'profile.sqlite'), projectDirs: [], demo: false };
  let server: AccServer | undefined;
  const launched: Array<{ cwd: string; prompt: string }> = [];
  const spawner: Spawner = { spawn(opts) {
    launched.push({ cwd: opts.cwd, prompt: opts.prompt });
    const child = spawn(process.execPath, ['-e', "const fs=require('node:fs');setInterval(()=>{if(fs.existsSync('finish.signal')){fs.unlinkSync('finish.signal');fs.writeFileSync('result.txt','Offline process result');process.exit(0)}},10)"], { cwd: opts.cwd, windowsHide: true, stdio: 'ignore' });
    return { lines: (async function* () {})(), done: new Promise<number>((resolve, reject) => { child.once('error', reject); child.once('exit', (code) => resolve(code ?? -1)); }), kill() { child.kill(); } };
  } };
  try {
    git(['init', '-q']); git(['config', 'user.name', 'Fixture']); git(['config', 'user.email', 'fixture@example.test']);
    writeFileSync(join(repo, 'original.txt'), 'Preserved'); git(['add', '.']); git(['commit', '-qm', 'base']); const baseSha = git(['rev-parse', 'HEAD']);
    server = await buildServer(env, { startSystem: false, spawner, workspaceRoot: join(root, 'workspaces') });
    const app = server.app;
    const post = (url: string, payload: object) => app.inject({ method: 'POST', url, headers: auth, payload });
    const get = async (url: string) => (await app.inject({ url, headers: auth })).json();
    await post('/api/projects', { dir: repo });
    const project = (await post('/api/portfolio/projects', { name: 'Task fixture', kind: 'app', goal: '', lifecycle: 'active', focus: true, manualPriority: 1 })).json().project;
    const source = (await get('/api/portfolio')).sources.find((s: { kind: string }) => s.kind === 'local');
    const imported = (await post('/api/portfolio/import', { projectId: project.id, sourceId: source.id })).json();
    const input = { projectId: project.id, repositoryId: imported.repositoryId, milestoneId: null, title: 'Offline task', outcome: 'Fixture result', scope: 'Only isolated fixture files', outOfScope: 'Publishing', acceptance: [{ id: randomUUID(), text: 'Independent check required', required: true }], dependsOn: [], priority: 1, status: 'ready', sourceRefs: [] };
    const task = (await post('/api/planning/tasks', input)).json().task;
    const route = `/api/planning/tasks/${task.id}/dispatch`;
    const request = { version: task.version, checkoutId: imported.checkoutId, baseSha, provider: 'codex', idempotencyKey: randomUUID() };
    expect((await app.inject({ method: 'POST', url: route, headers: host, payload: request })).statusCode).toBe(401);
    expect((await post(route, { ...request, task: 'Client replacement prompt' })).statusCode).toBe(400);
    const edited = await app.inject({ method: 'PUT', url: `/api/planning/tasks/${task.id}`, headers: auth, payload: { ...input, version: task.version, title: 'Exact revised task' } });
    expect(edited.statusCode).toBe(200);
    expect((await post(route, request)).statusCode).toBe(409);
    expect((await get('/api/runs')).runs).toEqual([]);
    request.version = edited.json().task.version;
    await post(`/api/projects/${source.id.slice(6)}/settings`, { feature: 'agents', enabled: false });
    expect((await post(route, request)).statusCode).toBe(409);
    expect(launched).toHaveLength(0);
    await post(`/api/projects/${source.id.slice(6)}/settings`, { feature: 'agents', enabled: true });
    const accepted = await post(route, request); expect(accepted.statusCode, accepted.body).toBe(200); const { runId } = accepted.json();
    const deadline = Date.now() + 30000;
    while (!launched.length && Date.now() < deadline) await new Promise((resolve) => setTimeout(resolve, 20));
    expect(launched).toHaveLength(1); expect(launched[0].cwd).not.toBe(repo); expect(launched[0].prompt).toContain('Exact revised task');
    const activeTask = (await get('/api/planning')).tasks[0]; expect(activeTask.status).toBe('active');
    expect((await app.inject({ method: 'PUT', url: `/api/planning/tasks/${task.id}`, headers: auth, payload: { ...input, version: activeTask.version } })).statusCode).toBe(409);
    writeFileSync(join(launched[0].cwd, 'finish.signal'), 'finish');
    while (server.runner.isLive(runId) && Date.now() < deadline) await new Promise((resolve) => setTimeout(resolve, 20));
    expect(server.runner.isLive(runId)).toBe(false);
    const run = (await get(`/api/runs/${runId}`)).run;
    expect(run).toMatchObject({ executionStatus: 'succeeded', exitCode: 0, taskId: task.id, taskVersion: request.version, baseSha, verifyVerdict: null, humanAction: null });
    const reviewedTask = (await get('/api/planning')).tasks[0]; expect(reviewedTask.status).toBe('awaiting_review');
    expect(readFileSync(join(repo, 'original.txt'), 'utf8')).toBe('Preserved'); expect(git(['status', '--porcelain'])).toBe('');
    expect((await post(route, request)).json()).toEqual({ runId }); expect(launched).toHaveLength(1);
    expect((await post(route, { ...request, provider: 'claude' })).statusCode).toBe(409);
    await server.close(); server = undefined;
    server = await buildServer(env, { startSystem: false, spawner, workspaceRoot: join(root, 'workspaces') });
    expect((await server.app.inject({ url: '/api/planning', headers: auth })).json().tasks[0]).toEqual(reviewedTask);
    expect((await server.app.inject({ url: `/api/runs/${runId}`, headers: auth })).json().run.executionStatus).toBe('succeeded');
    expect(launched).toHaveLength(1);
  } finally { await server?.close(); await rm(root, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 }); }
}, 120000);
