import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expect, it } from 'vitest';
import { openDb } from '../db';
import { runs, verificationEvidence, verificationAttempts, executionLocks } from '../db/schema';
import { workspaceEvidence } from './workspace';
import { Verifier } from './verification';
import { ApprovalStore } from './approvals';

it('binds an independent verify result to exact code and rejects later modifications', async () => {
  const root = mkdtempSync(join(tmpdir(), 'ado-verify-')); const repo = join(root, 'repo'); mkdirSync(repo);
  const git = (args: string[]) => execFileSync('git', args, { cwd: repo, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  const { db, sqlite } = openDb(':memory:');
  try {
    git(['init', '-q']); git(['config', 'user.name', 'Test']); git(['config', 'user.email', 'test@example.test']);
    writeFileSync(join(repo, 'package.json'), JSON.stringify({ scripts: { verify: 'node verify.cjs' } }));
    writeFileSync(join(repo, 'verify.cjs'), 'console.log("control test passed")');
    git(['add', '.']); git(['commit', '-qm', 'base']); const baseSha = git(['rev-parse', 'HEAD']);
    const evidence = await workspaceEvidence(repo, baseSha);
    db.insert(runs).values({ id: 'r', repoId: 'a', task: 'x', model: 'default', engineVersion: 1, status: 'done', startedTs: new Date().toISOString(), workspacePath: repo, baseSha, ...evidence }).run();
    const approvals = new ApprovalStore(db);
    const verifier = new Verifier(db, () => [], approvals);
    const target = { ...evidence, operation: 'result.accept', policyVersion: approvals.policyVersion('a') };
    const prepare = async () => ({ ...target, approvalId: (await verifier.prepareAcceptance('r', target)).id });
    expect((await verifier.verify('r')).verdict).toBe('pass');
    const attempt = db.select().from(verificationAttempts).get()!;
    expect(attempt).toMatchObject({ status: 'succeeded', processTermination: process.platform === 'win32' ? 'confirmed' : 'root_exited' });
    expect(db.select().from(verificationEvidence).get()?.attemptId).toBe(attempt.id);
    expect(db.select().from(executionLocks).all()).toEqual([]);
    expect(db.select().from(verificationEvidence).all()[0]).toMatchObject({ headSha: baseSha, diffDigest: evidence.diffDigest, exitCode: 0 });
    await expect(verifier.accept('r', { ...evidence, diffDigest: 'wrong' })).rejects.toThrow('exact reviewed');
    const concurrent = verifier.accept('r', await prepare());
    await expect(verifier.verify('r')).rejects.toThrow('already running');
    db.update(runs).set({ humanAction: 'corrected' }).run();
    await expect(concurrent).rejects.toThrow('changed during review');
    expect(db.select().from(runs).all()[0].humanAction).toBe('corrected');
    db.update(runs).set({ humanAction: null }).run();
    const reviewed = await prepare();
    expect((await verifier.accept('r', reviewed)).humanAction).toBe('accepted');
    await expect(verifier.accept('r', reviewed)).rejects.toThrow('already consumed');
    const changedReview = await prepare();
    writeFileSync(join(repo, 'verify.cjs'), 'throw new Error("changed")');
    await expect(verifier.accept('r', changedReview)).rejects.toThrow('stale');
    expect(db.select().from(runs).all()[0]).toMatchObject({ verifyVerdict: null, humanAction: null });
    db.update(runs).set({ verifyVerdict: 'pass', humanAction: 'accepted' }).run();
    const staleCorrection = verifier.accept('r', changedReview);
    db.update(runs).set({ humanAction: 'corrected' }).run();
    await expect(staleCorrection).rejects.toThrow('stale');
    expect(db.select().from(runs).all()[0]).toMatchObject({ verifyVerdict: null, humanAction: 'corrected' });
    db.update(runs).set({ verifyVerdict: 'pass', humanAction: 'accepted' }).run();
    await expect(verifier.verify('r')).rejects.toThrow(/changed/);
    expect(db.select().from(runs).all()[0]).toMatchObject({ verifyVerdict: null, humanAction: null });
  } finally { sqlite.close(); rmSync(root, { recursive: true, force: true }); }
}, 120000);
