import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { createServer } from 'node:net';
import { join, resolve } from 'node:path';
import { chromium } from 'playwright';
import { buildServer } from '../apps/server/src/app.ts';

execFileSync(process.execPath, [resolve('node_modules/vite/bin/vite.js'), 'build'], { cwd: resolve('apps/web'), env: { ...process.env, VITE_SERVER_URL: '' }, windowsHide: true, stdio: 'pipe' });
const root = mkdtempSync(join(tmpdir(), 'controlos-today-ui-'));
const port = await new Promise<number>((accept, reject) => { const socket = createServer(); socket.once('error', reject); socket.listen(0, '127.0.0.1', () => { const address = socket.address(); assert.ok(address && typeof address !== 'string'); socket.close(() => accept(address.port)); }); });
const token = randomBytes(24).toString('hex'), headers = { host: `127.0.0.1:${port}`, 'x-acc-token': token };
const server = await buildServer({ port, accToken: token, webOrigin: `http://127.0.0.1:${port}`, dbPath: join(root, 'profile.sqlite'), projectDirs: [], demo: false, serveWebDir: resolve('apps/web/dist') }, { startSystem: false, startScanner: false });
let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
try {
  const call = async (url: string, payload: object, method: 'POST' | 'PUT' = 'POST') => { const response = await server.app.inject({ method, url, headers, payload }); assert.equal(response.statusCode, 200, response.body); return response.json(); };
  const project = (await call('/api/portfolio/projects', { name: 'DEMO Today project', kind: 'app', goal: 'Synthetic planning acceptance fixture', lifecycle: 'active', focus: true, manualPriority: 1 })).project;
  const input = { projectId: project.id, repositoryId: null, milestoneId: null, title: 'DEMO locked focus', outcome: 'Review the synthetic result manually', scope: 'Fixture only', outOfScope: '', acceptance: [{ id: randomUUID(), text: 'Manual evidence reviewed', required: true }], dependsOn: [] as string[], priority: 1, status: 'ready', sourceRefs: [] };
  let focus = (await call('/api/planning/tasks', input)).task;
  const higher = (await call('/api/planning/tasks', { ...input, title: 'DEMO higher priority', priority: 5 })).task;
  const blocked = (await call('/api/planning/tasks', { ...input, title: 'DEMO blocked task', dependsOn: [higher.id] })).task;
  const snapshot = async () => (await server.app.inject({ url: '/api/planning', headers })).json();
  const base = await server.app.listen({ port, host: '127.0.0.1' });
  browser = await chromium.launch(); const page = await browser.newPage(), errors: string[] = [], shots: string[] = [];
  page.on('pageerror', error => errors.push(error.message)); mkdirSync('smoke-shots', { recursive: true });
  for (const width of [1536, 390]) {
    await page.setViewportSize({ width, height: 1000 }); await page.goto(`${base}/today`);
    await page.getByLabel('Access key').fill(token); await page.getByRole('button', { name: 'Connect', exact: true }).click();
    await page.getByRole('heading', { name: 'Your focus', exact: true }).waitFor();
    await page.getByLabel('Project focus', { exact: true }).selectOption(project.id);
    await page.getByLabel('Locked task', { exact: true }).selectOption(focus.id);
    await page.getByLabel('Minimum minutes: DEMO locked focus', { exact: true }).fill('10');
    await page.getByLabel('Maximum minutes: DEMO locked focus', { exact: true }).fill('25');
    const confirmEstimate = page.getByRole('button', { name: 'Use estimate for current task', exact: true });
    if (await confirmEstimate.count()) await confirmEstimate.click();
    await page.getByRole('button', { name: 'Save choices', exact: true }).click();
    await page.getByText('Choices saved in this profile.', { exact: true }).waitFor();
    const stored = (await server.app.inject({ url: '/api/planning/today/preferences', headers })).json();
    const { updatedTs: _updatedTs, ...otherWriter } = stored; void _updatedTs;
    await call('/api/planning/today/preferences', { ...otherWriter, availableMinutes: 45 }, 'PUT');
    await page.getByRole('button', { name: 'Save choices', exact: true }).click();
    await page.getByRole('alert').filter({ hasText: 'Saved Today choices changed' }).waitFor();
    assert.equal((await server.app.inject({ url: '/api/planning/today/preferences', headers })).json().availableMinutes, 45);
    await page.getByRole('button', { name: 'Load saved choices', exact: true }).click();
    await page.getByText('Saved choices loaded from this profile.', { exact: true }).waitFor();
    assert.equal(await page.getByLabel('Available minutes', { exact: true }).inputValue(), '45');
    await page.getByLabel('Available minutes', { exact: true }).fill('30');
    await page.getByRole('button', { name: 'Save choices', exact: true }).click();
    await page.getByText('Choices saved in this profile.', { exact: true }).waitFor();
    await page.reload();
    await page.getByLabel('Access key').fill(token); await page.getByRole('button', { name: 'Connect', exact: true }).click();
    await page.getByText('Saved choices loaded from this profile.', { exact: true }).waitFor();
    assert.equal(await page.getByLabel('Available minutes', { exact: true }).inputValue(), '30');
    assert.equal(await page.getByLabel('Locked task', { exact: true }).inputValue(), focus.id);
    assert.equal(await page.getByLabel('Maximum minutes: DEMO locked focus', { exact: true }).inputValue(), '25');
    const before = await snapshot();
    const suggest = page.getByRole('button', { name: 'Suggest next steps', exact: true });
    await suggest.focus(); await page.keyboard.press('Enter');
    const result = page.getByRole('region', { name: 'Today suggestions', exact: true });
    await result.getByRole('heading', { name: 'DEMO locked focus', exact: true }).waitFor();
    assert.equal(await result.locator('article').count(), 1);
    assert.ok((await result.innerText()).includes('User estimate; actual duration is unknown'));
    await result.locator('summary').click();
    assert.ok((await result.innerText()).includes('Outside your locked task or project focus'));
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.evaluate(() => window.scrollTo(0, 0));
    const shot = `smoke-shots/today-${width}.png`; await page.screenshot({ path: resolve(shot), fullPage: true }); shots.push(shot);
    assert.deepEqual(await snapshot(), before);
    await page.getByLabel('Maximum minutes: DEMO locked focus', { exact: true }).fill('31');
    assert.equal(await result.count(), 0);
    await suggest.click(); await page.getByText('No task fits this focus and time window. Review the reasons below.', { exact: true }).waitFor();
    await result.locator('summary').click(); assert.ok((await result.innerText()).includes('Upper estimate exceeds your available time'));
    await page.getByLabel('Maximum minutes: DEMO locked focus', { exact: true }).fill('25');
    focus = (await call(`/api/planning/tasks/${focus.id}`, { ...input, version: focus.version, outcome: `Changed synthetic outcome ${width}` }, 'PUT')).task;
    await suggest.click(); await page.getByRole('alert').filter({ hasText: 'Task estimate is stale' }).waitFor();
    assert.equal(await result.count(), 0);
    await page.getByRole('button', { name: 'Refresh planning', exact: true }).click();
    await page.getByRole('alert').filter({ hasText: 'Task changed' }).waitFor();
    await page.getByLabel('Maximum minutes: DEMO locked focus', { exact: true }).fill('26');
    await suggest.click(); await result.getByRole('heading', { name: 'DEMO locked focus', exact: true }).waitFor();
    await page.getByLabel('Locked task', { exact: true }).selectOption(blocked.id);
    await page.getByLabel('Minimum minutes: DEMO blocked task', { exact: true }).fill('5');
    await page.getByLabel('Maximum minutes: DEMO blocked task', { exact: true }).fill('10');
    await suggest.click(); await page.getByText('No task fits this focus and time window. Review the reasons below.', { exact: true }).waitFor();
    await result.locator('summary').click(); assert.ok((await result.innerText()).includes('Dependencies are not accepted'));
    await page.route('**/api/planning/today', route => route.abort());
    await suggest.click(); await page.getByRole('alert').waitFor(); assert.equal(await result.count(), 0);
    await page.unroute('**/api/planning/today');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    const oldInput = { ...input, title: `DEMO old estimate ${width}` };
    const retainedTask = (await call('/api/planning/tasks', oldInput)).task;
    const savedBefore = (await server.app.inject({ url: '/api/planning/today/preferences', headers })).json();
    const retainedChoices = await call('/api/planning/today/preferences', { version: savedBefore.version, availableMinutes: 30, projectId: project.id, lockedTaskId: focus.id, estimates: [
      { taskId: focus.id, taskVersion: focus.version, minMinutes: 10, maxMinutes: 26 },
      { taskId: retainedTask.id, taskVersion: retainedTask.version, minMinutes: 5, maxMinutes: 10 },
    ] }, 'PUT');
    await call(`/api/planning/tasks/${retainedTask.id}`, { ...oldInput, version: retainedTask.version, status: 'archived' }, 'PUT');
    await page.getByRole('button', { name: 'Load saved choices', exact: true }).click();
    const retained = page.getByRole('region', { name: 'Other retained estimates', exact: true });
    await retained.getByText('This estimate is stale and prevents saving.', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Save choices', exact: true }).click();
    await page.getByRole('alert').filter({ hasText: 'Task estimate is stale' }).waitFor();
    await page.evaluate(() => window.scrollTo(0, 0));
    const retainedShot = `smoke-shots/today-retained-${width}.png`; await page.screenshot({ path: resolve(retainedShot), fullPage: true }); shots.push(retainedShot);
    await retained.getByRole('button', { name: `Remove retained estimate: ${retainedTask.title}`, exact: true }).click();
    assert.equal(await retained.count(), 0);
    assert.deepEqual((await server.app.inject({ url: '/api/planning/today/preferences', headers })).json(), retainedChoices);
    assert.equal(await page.getByLabel('Locked task', { exact: true }).inputValue(), focus.id);
    await page.getByRole('button', { name: 'Save choices', exact: true }).click();
    await page.getByText('Choices saved in this profile.', { exact: true }).waitFor();
    const cleaned = (await server.app.inject({ url: '/api/planning/today/preferences', headers })).json();
    assert.deepEqual(cleaned.estimates, retainedChoices.estimates.filter((e: { taskId: string }) => e.taskId === focus.id));
    assert.equal(cleaned.lockedTaskId, focus.id);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  }
  assert.deepEqual((await server.app.inject({ url: '/api/runs', headers })).json().runs, []);
  assert.deepEqual(errors, []);
  const hash = (path: string) => createHash('sha256').update(readFileSync(path)).digest('hex');
  const sources = ['scripts/probe-today.mts', 'apps/web/src/pages/TodayPage.tsx', 'apps/web/src/main.tsx', 'apps/web/src/chrome/MobileNav.tsx', 'apps/server/src/projects/today.ts', 'apps/server/src/projects/todayLocks.ts', 'apps/server/src/projects/todayPreferences.ts', 'apps/server/drizzle/0020_today_preferences.sql', 'apps/server/src/app.ts', 'packages/shared/src/today.ts'];
  const assets = ['apps/web/dist/index.html', ...readdirSync('apps/web/dist/assets').filter(name => name.endsWith('.js') || name.endsWith('.css')).map(name => `apps/web/dist/assets/${name}`)];
  const evidence = { date: new Date().toISOString(), baseRevision: execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(), environment: { platform: process.platform, arch: process.arch, node: process.version, chromium: browser.version() }, viewports: [1536, 390], checks: ['30-minute locked focus', 'keyboard submit', 'uncertain user estimate', 'over-budget exclusion', 'no higher-priority replacement', 'blocked dependencies', 'stale version rejection', 'explicit estimate refresh', 'network failure clears old proposal', 'saved choices restored after browser reload', 'concurrent writer rejected without overwrite', 'explicit load of newer choices', 'no planning mutation by proposal', 'zero runs', 'no horizontal overflow or page errors'], sourceSha256: Object.fromEntries(sources.map(path => [path, hash(path)])), assetSha256: Object.fromEntries(assets.map(path => [path, hash(path)])), screenshotSha256: Object.fromEntries(shots.map(path => [path, hash(path)])), scope: 'Synthetic local profile through production API and built renderer, with profile-local saved choices and explicit concurrent-write recovery. No agent, calendar, external provider or execution-policy acceptance.' };
  writeFileSync('docs/controlos/today-ui-evidence.json', JSON.stringify(evidence, null, 2) + '\n');
  console.log(JSON.stringify({ result: 'passed', ...evidence.environment, screenshots: shots, fixture: root }));
} finally { await browser?.close(); await server.close(); }
